[build-options]
  observabilityIncluded = true

[package]
  distribution = "2201.2.3"
  export = ["worldbank_data_to_covid19_statistics"]
  icon = "docs/icon.png"
  keywords = ["Kind/Sample","Type/RestApi","Category/Service","Internal/http"]
  name = "worldbank_data_to_covid19_statistics"
  org = "erkas"
  version = "1.2.1"

